import type { Candidate } from "../../types/candidates/candidates";

export const initialCandidates: Candidate[] = [
  {
    id: crypto.randomUUID(),
    firstName: "Liam",
    lastName: "Anderson",
    contact: { email: "liam.anderson@example.com", phone: "09171234501" },
    stage: "applied",
    status: "active",
    skills: ["React", "TypeScript"],
    appliedAt: Date.now() - 100000000,
    updatedAt: null,
  },
  {
    id: crypto.randomUUID(),
    firstName: "Emma",
    lastName: "Garcia",
    contact: { email: "emma.garcia@example.com", phone: "09171234502" },
    stage: "applied",
    status: "active",
    skills: ["Node.js", "Express"],
    appliedAt: Date.now() - 90000000,
    updatedAt: Date.now() - 80000000,
  },
  {
    id: crypto.randomUUID(),
    firstName: "Noah",
    middleName: "James",
    lastName: "Martinez",
    contact: { email: "noah.martinez@example.com", phone: "09171234503" },
    stage: "applied",
    status: "active",
    skills: ["Python", "Django"],
    appliedAt: Date.now() - 80000000,
    updatedAt: Date.now() - 70000000,
  },
  {
    id: crypto.randomUUID(),
    firstName: "Olivia",
    lastName: "Lee",
    contact: { email: "olivia.lee@example.com", phone: "09171234504" },
    stage: "applied",
    status: "active",
    skills: ["UI/UX", "Figma"],
    appliedAt: Date.now() - 70000000,
    updatedAt: Date.now() - 60000000,
  },
  {
    id: crypto.randomUUID(),
    firstName: "Elijah",
    lastName: "Brown",
    contact: { email: "elijah.brown@example.com", phone: "09171234505" },
    stage: "applied",
    status: "active",
    skills: ["Java", "Spring"],
    appliedAt: Date.now() - 60000000,
    updatedAt: Date.now() - 50000000,
  },
  {
    id: crypto.randomUUID(),
    firstName: "Ava",
    lastName: "Davis",
    contact: { email: "ava.davis@example.com", phone: "09171234506" },
    stage: "applied",
    status: "active",
    skills: ["Project Management"],
    appliedAt: Date.now() - 50000000,
    updatedAt: Date.now() - 40000000,
  },
  {
    id: crypto.randomUUID(),
    firstName: "William",
    lastName: "Wilson",
    contact: { email: "william.wilson@example.com", phone: "09171234507" },
    stage: "applied",
    status: "active",
    skills: ["C++", "Embedded Systems"],
    appliedAt: Date.now() - 40000000,
    updatedAt: Date.now() - 30000000,
  },
  {
    id: crypto.randomUUID(),
    firstName: "Sophia",
    middleName: "Grace",
    lastName: "Taylor",
    contact: { email: "sophia.taylor@example.com", phone: "09171234508" },
    stage: "applied",
    status: "active",
    skills: ["Go", "Microservices"],
    appliedAt: Date.now() - 30000000,
    updatedAt: Date.now() - 20000000,
  },
  {
    id: crypto.randomUUID(),
    firstName: "James",
    lastName: "Moore",
    contact: { email: "james.moore@example.com", phone: "09171234509" },
    stage: "applied",
    status: "active",
    skills: ["Angular", "RxJS"],
    appliedAt: Date.now() - 20000000,
    updatedAt: Date.now() - 10000000,
  },
  {
    id: crypto.randomUUID(),
    firstName: "Isabella",
    lastName: "Clark",
    contact: { email: "isabella.clark@example.com", phone: "09171234510" },
    stage: "applied",
    status: "active",
    skills: ["QA", "Automation"],
    appliedAt: Date.now() - 10000000,
    updatedAt: null,
  },
];