import { initialInterviewers } from './../interviewer/initialInterviewer';
import type { InterviewTs } from "../../types/interview/interview";
import{ initialCandidates } from "../candidates/initialCandidates";


export const initialInterviews: InterviewTs[] = [
  {
    id: crypto.randomUUID(),
    candidateId: initialCandidates[0].id,
    interviewerId: initialInterviewers[0].id,
    title: "Frontend Technical Interview",
    date: "2026-04-05",
    startTime: "09:00",
    endTime: "10:00",
    type: "technical",
    status: "scheduled",
    notes: "React hooks and state management.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    updatedAt: null,
  },
  {
    id: crypto.randomUUID(),
    candidateId: initialCandidates[1].id,
    interviewerId: initialInterviewers[1].id,
    title: "Backend Technical Interview",
    date: "2026-04-05",
    startTime: "10:30",
    endTime: "11:30",
    type: "technical",
    status: "scheduled",
    notes: "API design and database queries.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
    updatedAt: null,
  },
  {
    id: crypto.randomUUID(),
    candidateId: initialCandidates[2].id,
    interviewerId: initialInterviewers[2].id,
    title: "QA Interview",
    date: "2026-04-06",
    startTime: "13:00",
    endTime: "14:00",
    type: "technical",
    status: "scheduled",
    notes: "Automation testing and edge cases.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    updatedAt: null,
  },
  {
    id: crypto.randomUUID(),
    candidateId: initialCandidates[3].id,
    interviewerId: initialInterviewers[3].id,
    title: "HR Screening",
    date: "2026-04-06",
    startTime: "14:30",
    endTime: "15:00",
    type: "hr-screening",
    status: "scheduled",
    notes: "Culture fit and communication.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
  {
    id: crypto.randomUUID(),
    candidateId: initialCandidates[4].id,
    interviewerId: initialInterviewers[4].id,
    title: "Managerial Interview",
    date: "2026-04-07",
    startTime: "09:00",
    endTime: "10:00",
    type: "final",
    status: "scheduled",
    notes: "Leadership and decision-making.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    updatedAt: null,
  },
 
];
